ENCD-4376 ATAC qc metric
ENCODE-DCC/encoded pull request #2682
Opened 2019-03-26 22:08 UTC by gabdank

2019-03-27 13:48 UTC, jahilton requested changes
Add empty line to the end of files
Add assay_term_name as a facet to the schema

2019-03-27 16:27 UTC, jahilton requested changes
line 37 src/encoded/tests/test_schema_quality_metric.py, unnecessary empty line
line 12 src/encoded/tests/data/inserts/atac_quality_metric.json, unnecessary empty line

2019-03-27 16:30 UTC, jahilton requested changes
line 12 src/encoded/tests/data/inserts/atac_quality_metric.json, unnecessary empty line
line 37 src/encoded/tests/test_schema_quality_metric.py, unnecessary empty line

2019-03-27 19:19 UTC, jahilton approved these changes

2019-04-11 19:18 UTC, leepc12 approved these changes

2019-06-04 21:26 UTC, closed without merging