ENCD-5080-add-library-property-strandedness
ENCODE-DCC/encoded pull request #3186
Opened 2020-03-05 23:38 UTC by iyoungworth

2020-03-11 19:44 UTC, gabdank requested changes
can you please include enums forward/reverse in inserts?

2020-03-11 19:57 UTC, iyoungworth commented
Absolutely- sorry about that, I thought I had done so. I made two "strand-specific" entries to "forward" and two others to "reverse".

2020-03-12 05:00 UTC, gabdank submitted a review, later dismissed

2020-03-16 14:58 UTC, gabdank approved these changes

2020-03-17 23:32 UTC, merged