ENCD-5123-expt-audit-processed-files-analyses
ENCODE-DCC/encoded pull request #3192
Opened 2020-03-09 23:20 UTC by bonitalam

2020-03-12 05:08 UTC, gabdank requested changes

2020-03-12 05:08 UTC, gabdank commented on src/encoded/audit/experiment.py
> +                    yield AuditFailure('inconsistent analyses files', detail, level='INTERNAL_ACTION')
I think this code is incorrect. Should have been something like:
`
for analysis in value['analyses']:
...
`
and I think that it should not be file_object in analysis, but file_object['@id'] in analysis

2020-03-13 16:57 UTC, gabdank requested changes
please add test for a situation where the audit is not triggered because all the processed files are in analyses.

2020-03-16 15:11 UTC, gabdank requested changes

2020-03-16 15:11 UTC, gabdank commented on src/encoded/audit/experiment.py
> +            if analysis_file not in processed_data:
@bonitalam please update the variable names. processed_data is a dictionary, so every time you do something like "for processed_file in processed_data" or "if analysis_file in processed_data" - you actually iterating over or checking for the existence of a file_id in processed_data dictionary keys. I propose to make it more clear by renaming in the proper places "processed_file" into "processed_file_id" and similarly "analysis_file" into "analysis_file_id", I would also make it clear that you are traversing keys of a dictionary by using "processed_data.keys()"

2020-03-17 22:24 UTC, bonitalam commented
I had to move out the links and audit detail lines, so that only one audit should be raised (listing all the files) rather than multiple.

2020-03-18 05:44 UTC, gabdank approved these changes

2020-03-18 14:10 UTC, gabdank submitted a review, later dismissed

2020-03-19 04:37 UTC, gabdank approved these changes

2020-03-20 19:58 UTC, merged