ENCD-5229-fix-run-type-dependency
ENCODE-DCC/encoded pull request #3270
Opened 2020-04-22 21:11 UTC by jenjou

2020-04-24 00:06 UTC, gabdank requested changes
@jenjou can you please add schema tests that make sure the dependency behaves properly, like posting FASTQ not PacBio and making sure run_type is required, and few more fixtures to have dependencies in check for future schema updates?

2020-04-24 21:38 UTC, jenjou commented
There is an existing test_no_runtype_readlength_dependency so I just added test_no_runtype_dependency as I'm not sure what else would be useful.

2020-04-27 17:05 UTC, gabdank submitted a review, later dismissed

2020-04-30 21:13 UTC, hitz commented
@jenjou has conflicts with tests/fixtures/schemas/file.py  please rebase and force-push

2020-04-30 23:54 UTC, gabdank approved these changes

2020-05-01 00:50 UTC, merged