ENCD-5244-add-new-enums-for-DAC-pipeline
ENCODE-DCC/encoded pull request #3286
Opened 2020-04-28 01:58 UTC by jenjou

2020-04-28 21:15 UTC, gabdank requested changes
@jenjou can you please add inserts for the steps and for the file types?

2020-04-28 23:39 UTC, jenjou commented
> @jenjou can you please add inserts for the steps and for the file types?

Added inserts

2020-04-29 14:45 UTC, gabdank submitted a review, later dismissed

2020-04-30 21:16 UTC, hitz commented
@jenjou also has conflicts with tests (data/inserts/file.json)... sorry.  Please rebase, fix conflict, force-push.

2020-04-30 23:55 UTC, gabdank approved these changes

2020-05-01 00:49 UTC, merged