ENCD-4913-fix-filtered-url-in-matrix
ENCODE-DCC/encoded pull request #3294
Opened 2020-05-05 16:54 UTC by zoldello

2020-05-06 23:26 UTC, forresttanaka requested changes
I tried a local build as well as your demo, but I still see the repeated properties. For example, https://encd-4913-e2926704d-phil.demo.encodedcc.org/search/?type=Experiment&status=released&assay_title=TF+ChIP-seq. If you click the TF ChIP-seq header column, I still get two of the same assay_title properties in the query string.

2020-05-06 23:26 UTC, forresttanaka commented on src/encoded/static/components/matrix_experiment.js
> +    const searchUrl = '/search/?type=Experiment&status=released';
I feel uncomfortable hard-coding this. I’d prefer to do something like taking the search_base and removing any part of it that matches a column property before appending that column property.

2020-05-06 23:28 UTC, forresttanaka commented
I’m also getting a key error in the Javascript console, at least when running locally (I didn’t check when I had your demo up).

”Encountered two children with the same key, `Histone ChIP-seq`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.“

2020-05-11 16:08 UTC, forresttanaka submitted a review, later dismissed
OK, though I thought you were going to use the QueryString module to do this, since that’s what it does. I’m still not clear what Ben wants with stripping other selected facets, because it seems strange that going from matrix to search is different than going from search to matrix, but Jennifer can figure that out I guess.

2020-05-15 17:03 UTC, forresttanaka approved these changes
You can also use nested string templates, which is another option to the .join('').

2020-05-15 17:08 UTC, zoldello commented
@forresttanaka Good point. I did not use string template because it seemed awkward to have a string template inside a string template. I will consider it for next time.

2020-05-20 22:49 UTC, merged