ENCD-5031-make-facets-collapsible
ENCODE-DCC/encoded pull request #3341
Opened 2020-06-01 18:50 UTC by zoldello

2020-06-15 19:52 UTC, forresttanaka requested changes
The main feedback: I think the localstorage code should be close to the code handling the expand/collapse state so that all facet types can use it without needing to worry much about it.

2020-06-15 19:52 UTC, forresttanaka commented on src/encoded/static/components/facets/date_selector.js
> +    /** toogles facets */
“Toggles”

2020-06-15 19:52 UTC, forresttanaka commented on src/encoded/static/components/facets/defaults.js
> +const preopenedFacetList = ['status', 'perturbed', 'assay_slims', 'biosample_ontology.term_name', 'target.label'];
On Slack I think, Ben said the facets opened by default would be defined in the schema. Was this decided against? No problem defining them here as well, but the schema seemed like the obvious place so that if you delete or add a facet to the schema that should be expanded by default, you wouldn’t also have to modify this array.

2020-06-15 19:52 UTC, forresttanaka commented on src/encoded/static/components/facets/defaults.js
> +        if (toggleFacets) {
Why wouldn’t `toggleFacets` exist?

2020-06-15 19:52 UTC, forresttanaka commented on src/encoded/static/components/facets/defaults.js
> +    }, []); // eslint-disable-line react-hooks/exhaustive-deps
I feel like this code should be handled by search.js, not the default facet. If we wanted to make the date-selector facet or the exists facet also collapse (and I felt surprised they don’t), then we’ll have to copy this code to the other kinds of default and custom facets. I think each facet component should be told through props if they appear expanded or not. We’ll still need a trigger callback, but search.js should be the one and only place that stores the expanded/collapsed states. The facet and title components should only know whether their particular facet appears expanded or not.

2020-06-15 19:52 UTC, forresttanaka commented on src/encoded/static/components/facets/defaults.js
> +    };
Like here, `toggleFacets` should just tell `<Search>` that the user clicked the expand/collapsed trigger. It shouldn’t care how that gets recorded. Let search.js worry about the current states and storing them.

2020-06-15 19:52 UTC, forresttanaka commented on src/encoded/static/components/facets/defaults.js
> +    };
I think this and `handleExpanderClick` should either be a service provided by search.js, or should be in a custom hook that all facet types can use. Or maybe just be implemented once in TitleComponent.

2020-06-15 19:52 UTC, forresttanaka commented on src/encoded/static/components/facets/exists.js
>      />
`DefaultExistsFacet` doesn’t seem to use these new props, nor does `DefaultDateSelector`.

2020-06-22 02:05 UTC, zoldello commented
closed in lieu of SNO-157

2020-06-22 02:05 UTC, closed without merging