ENCD-5062-add-image-icon-on-report-page
ENCODE-DCC/encoded pull request #3449
Opened 2020-07-24 15:46 UTC by zoldello

2020-07-27 17:32 UTC, forresttanaka requested changes
Nice capability.

2020-07-27 17:32 UTC, forresttanaka commented on src/encoded/schemas/image.json
> +        }
Are these two properties needed if they’re calculated? Neither the datasets nor the experiment have a “files” property in their schemas, yet they have a calculated `files` property.

2020-07-27 17:32 UTC, forresttanaka commented on src/encoded/types/image.py
> +        return self.jsonld_id(request) + attachment['href']
Seems like this should be snake case. You might also want to comment these, as it took me quite a while to figure out why you had two properties with exactly the same value. In the future, I’d like to make the row cells customizable through a registration system, just like facets, and we might not need two properties with the same value at that stage.

2020-07-27 17:32 UTC, forresttanaka commented on src/encoded/static/components/image.js
> +    }
I feel like what might be cleaner is if, rather than modifying `Attachment` which expects an attachment, that you modify `Image` to not call `Attachment` anymore, and instead use the code you have here. That way you don’t modify `Attachment` which gets used elsewhere for things with attachments.

Do you need the extra surrounding `<div>`?

2020-07-27 17:32 UTC, forresttanaka commented on src/encoded/static/components/search.js
> -                    <p className="type meta-title">Image</p>
I know removing the “Image” type was a request from Meenakshi, but it feels odd that `Image` stands alone as the only search result without a type (I think), and instead I feel we should keep this and add the status. I’ll comment in the ticket about that.

2020-07-27 17:32 UTC, forresttanaka commented on src/encoded/static/components/search.js
> +                    <a href={result['@id']} className="result-item__link">{result['@id']}</a>
Meenakshi asked for the UUID here, but I doubt it really matters, and she might have meant @id.

2020-07-27 21:19 UTC, zoldello commented on src/encoded/static/components/search.js
> +                    <a href={result['@id']} className="result-item__link">{result['@id']}</a>
I am showing the @id... right?

2020-07-27 21:21 UTC, forresttanaka commented on src/encoded/static/components/search.js
> +                    <a href={result['@id']} className="result-item__link">{result['@id']}</a>
Right. Just saying that’s not what she asked for, but my guess is that it won’t matter to her.

2020-07-27 21:55 UTC, hitz requested changes

2020-07-27 21:55 UTC, hitz commented on src/encoded/schemas/image.json
> +        }
In fact if they are calculated they should NOT be here.  There are a few exceptions for properties that can be submitted or calculated.

2020-07-27 21:55 UTC, hitz commented on src/encoded/types/image.py
> +        return self.jsonld_id(request) + attachment['href']
I agree

2020-07-28 15:23 UTC, forresttanaka approved these changes
Though technically, “thumbnail” is one word, not “thumb nail.”

2020-07-30 03:12 UTC, merged