ENCD-5527-add-cut-and-tag-assay
ENCODE-DCC/encoded pull request #3524
Opened 2020-09-11 05:31 UTC by yunhailuo

2020-09-11 14:56 UTC, jnau requested changes
need to add minor changes to all (40?) change logs that use mixins.json with addition of assay name. other than that, code looks good.

2020-09-11 18:30 UTC, jnau approved these changes, later dismissed

2020-09-16 15:32 UTC, jnau approved these changes, later dismissed

2020-09-17 04:45 UTC, hitz commented
There are random doc conflicts so I just resolved them.

2020-09-17 05:31 UTC, hitz approved these changes
force approval my own merge comments on comments.

2020-09-17 05:33 UTC, merged