VALIS-9-preserve-coordinate-on-tab-out
ENCODE-DCC/encoded pull request #3620
Opened 2020-11-10 03:44 UTC by zoldello

2020-11-10 21:41 UTC, emro requested changes
This is terrific. I like the updates that you made a lot - the new functions and caching. It works super well too. Huge improvement. I just found typos, very minor.

2020-11-10 21:41 UTC, emro commented on src/encoded/static/components/genome_browser.js
> + * Get default coordinats to the genome browser
"coordinates"

2020-11-10 21:41 UTC, emro commented on src/encoded/static/components/genome_browser.js
> + * @param {string} assemblyAnnotation Assemnly information
"Assembly"

2020-11-10 21:41 UTC, emro commented on src/encoded/static/components/genome_browser.js
> + * @param {string} scrollLocation, in format: "chr{contig} {x0}bp to {x1}bp, where contig, x0 and x2  and numbersp"
"are numbers"?

2020-11-10 21:41 UTC, emro commented on src/encoded/static/components/genome_browser.js
> + * @param {string} scrollLocation, in format: "chr{contig} {x0}bp to {x1}bp, where contig, x0 and x2  and numbersp"
Also, I think it can also be in `Mbp`. I was actually wondering if it could be in anything other than bp and Mbp - do you know?

2020-11-10 21:41 UTC, emro commented on src/encoded/static/components/genome_browser.js
> +    const gVState = ignoreCache ? null : window.sessionStorage.getItem(GV_COORDINATES_KEY);
Caching the coordinates information is a great improvement -- thank you!

2020-11-17 17:10 UTC, zoldello commented
@emro  I created ENCD-5632 off this since this is a ENCD issue.

2020-11-17 17:10 UTC, closed without merging