ENCD-5600-add-Capture-Hi-C-and-snRNA-seq
ENCODE-DCC/encoded pull request #3626
Opened 2020-11-12 19:47 UTC by yunhailuo

2020-11-12 21:12 UTC, jnau requested changes
Can you add minor changes to /schemas/changelogs for award, mixins, and software?

2020-11-12 21:59 UTC, yunhailuo commented
> Can you add minor changes to /schemas/changelogs for award, mixins, and software?

Thanks. Added

2020-11-12 22:55 UTC, jnau submitted a review, later dismissed

2020-11-15 02:16 UTC, jnau approved these changes

2020-11-18 21:20 UTC, merged