ENCD-5665-tie-eslint-to-circleci
ENCODE-DCC/encoded pull request #3671
Opened 2021-01-08 17:34 UTC by zoldello

2021-01-08 21:00 UTC, paul-sud requested changes
I think there is some unneeded config, and also a potential to speed up the linting.

2021-01-08 21:00 UTC, paul-sud commented on .circleci/config.yml
> +      - buildout
For speed, maybe it is possible to get away with not running full buildout. Maybe just `npm` install would be enough. Even more minimal might be to skip npm install entirely, assuming `eslint` doesn't require access to dependencies.

2021-01-08 21:00 UTC, paul-sud commented on .circleci/config.yml
> +          path: test-results
You don't need these two lines, since I don't think eslint is generating any results files.

2021-01-08 21:00 UTC, paul-sud commented on .circleci/config.yml
> +            mkdir -p test-results/eslint
I don't think you need this line, it doesn't look like eslint has any results to report.

2021-01-08 21:08 UTC, zoldello commented on .circleci/config.yml
> +      - buildout
won't doing "npm install" be slower as it install all packages and not just want is needed?

2021-01-08 21:11 UTC, paul-sud commented on .circleci/config.yml
> +      - buildout
buildout installs the python stuff, then runs `npm install`, among other things. So I'd expect that `npm install` on its own would be faster than full buildout.

2021-01-08 23:57 UTC, zoldello commented on .circleci/config.yml
> +      - buildout
Done

2021-01-08 23:57 UTC, zoldello commented on .circleci/config.yml
> +          path: test-results
remove

2021-01-08 23:57 UTC, zoldello commented on .circleci/config.yml
> +            mkdir -p test-results/eslint
removed

2021-01-08 23:58 UTC, zoldello commented on .circleci/config.yml
> +      -  buildout
I tried an image. I got issues with python needing to be installed. So, to keep things simple, I used "buildout". There does no seems to considerable lag

2021-01-09 00:00 UTC, zoldello commented on .circleci/config.yml
> +      -  buildout
@paul-sud  I tried an image. I got issues with python needing to be installed. So, to keep things simple, I used "buildout". There does no seems to considerable lag

2021-01-09 00:05 UTC, paul-sud commented on .circleci/config.yml
> +      -  buildout
Ok if you're fine with it then it's fine by me

2021-01-09 00:06 UTC, paul-sud submitted a review, later dismissed
LGTM

2021-01-09 02:54 UTC, zoldello commented
Note- The build will fail until the code base is rebased with ENCD-5661.

2021-01-13 03:18 UTC, zoldello commented
@paul-sud  I fixed ESlint errors rather than wait on ENCD-5661.

2021-01-13 16:54 UTC, paul-sud approved these changes, later dismissed
JS changes look fine.

2021-01-19 22:22 UTC, paul-sud approved these changes
LGTM

2021-01-21 01:35 UTC, merged