ENCD-5678-update-frontend-documentation
ENCODE-DCC/encoded pull request #3689
Opened 2021-01-26 22:38 UTC by zoldello

2021-01-29 20:15 UTC, emro requested changes
There were a number of extra spaces which should be omitted. I have some wording suggestions which you should feel free to ignore. A couple typos should be fixed. It looks good though! All the links will be very helpful.

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +It is important to make sure new Javascript code satisifies [ESLint](https://eslint.org/) rules, otherwise, the CircleCI under  (ci/circleci: eslint) check will fail the build.
Extra space after "under"?

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +You can check for and correct [ESLint](https://eslint.org/) violations either through the command line or with a plugin to a text editor. Either way suffices as long  as violations are corrected.
Extra space after "long"?

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +`./node_modules/eslint/bin/eslint.js src/encoded/static/components/`
I'd capitalize "for" because you do in line 216.

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +You can also fix violation for just one file (e.g datacolor.js) by  running:
Extra space after "by"?

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +There are many [YouTube](https://www.youtube.com/results?search_query=eslint+command+line) videos on this  topic. Here is one [discussing command line](https://www.youtube.com/watch?v=txJEn1Fn0Gg).
Extra space after "this"?

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +Widely used code text editors generally have extensions that allows you to visually detect [ESLint](https://eslint.org/) violations by seeing a squiggly under the code in question. They also display
"that allow" not "that allows"

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +Widely used code text editors generally have extensions that allows you to visually detect [ESLint](https://eslint.org/) violations by seeing a squiggly under the code in question. They also display
Extra space after "display"

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +Widely used code text editors generally have extensions that allows you to visually detect [ESLint](https://eslint.org/) violations by seeing a squiggly under the code in question. They also display
This is sort of a confusing sentence though I do know what you mean. Maybe "Editors display information pertaining to the violated rule on hover as well as automated corrections which can be selected and applied by clicking.

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +It is important to make sure new style sheets  satisifies [StyleLint](https://stylelint.io/) rules, otherwise, the CircleCI under  (ci/circleci: stylelint) check will fail the build.
Extra space after "sheets" and "satisfies" should be "satisfy"

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +It is important to make sure new style sheets  satisifies [StyleLint](https://stylelint.io/) rules, otherwise, the CircleCI under  (ci/circleci: stylelint) check will fail the build.
Extra space after "under"

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +
Extra space after "long"

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +The  format for checking for [StyleLint](https://stylelint.io/) violations is:
Extra space after "the"

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +`./node_modules/stylelint/bin/stylelint.js src/encoded/static/scss/ --fix`
No comma after "folder"

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +`./node_modules/stylelint/bin/stylelint.js src/encoded/static/components/style.scss -- fix`
Extra space

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +You can search on [YouTube](https://www.youtube.com/results?search_query=stylelint+) to see if there are any videos that illustrate using the command line with  [StyleLint](https://stylelint.io/).  I
Extra spaces

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +Widely used code text editors generally have extensions that allows you to visually detect [StyleLint Command line interface Documention page](https://stylelint.io/user-guide/usage/cli) violations by
"allows" should be "allow"

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +Widely used code text editors generally have extensions that allows you to visually detect [StyleLint Command line interface Documention page](https://stylelint.io/user-guide/usage/cli) violations by
"allow you to detect by seeing" is sort of wordy construction, you could just say "Widely used code text editors have extensions that highlight code violations with underlines/emphasis, and often display information about rule violations and sometimes automated corrections on mouseover...."

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +Widely used code text editors generally have extensions that allows you to visually detect [StyleLint Command line interface Documention page](https://stylelint.io/user-guide/usage/cli) violations by
"appropriate" not "appropiate"

2021-01-29 20:15 UTC, emro commented on docs/front-end-overview.md
> +You can search on [YouTube](https://www.youtube.com/results?search_query=stylelint+) to see if there are any vidoes that illustrate using text editor extension with  [StyleLint](https://stylelint.io/
Extra space after "with"

2021-01-31 05:17 UTC, zoldello commented
@emro I will fix all double-spaces. However, in general, md files ignores the extra space just like HTML.

2021-02-01 17:29 UTC, emro requested changes
Two more small changes! Thank you for making all the other edits.

2021-02-01 17:29 UTC, emro commented on docs/front-end-overview.md
> +ENCODE uses [ESLint](https://eslint.org/) to automate enforcement of Javascript code quality and standards. It is also a tool that help developers learn good Javascript practices. ESLint inspects all
This should be "helps" actually.

2021-02-01 17:29 UTC, emro commented on docs/front-end-overview.md
> +Here is a collection of extenstions for [popular code editors](https://stylelint.io/user-guide/integrations/editor)
I think I missed this in the first review - sorry! - "extenstions" should be "extensions". Also in the text above which you did not change "Documention" should be "Documentation".

2021-02-01 18:05 UTC, emro approved these changes

2021-02-03 02:17 UTC, merged