ENCD-5758 Add biological replicate to cart facets
ENCODE-DCC/encoded pull request #3759
Opened 2021-03-04 22:04 UTC by forresttanaka

I added a method to convert the biological replicate array into a displayable, comma-separated string, so I added a new `getValue` transform that any facet can use if needed. So far, we only need it for the biological replicates.

2021-03-05 23:08 UTC, zoldello reviewed
My comments are questions. They center on "files" as a parameter.

2021-03-05 23:08 UTC, zoldello commented on src/encoded/static/components/cart/cart.js
> +const analysisSorter = (facetTerms, files, analyses) => (
Why is there "files" as a parameter when it is not used? Your jsdoc comment does not explain why.

2021-03-05 23:08 UTC, zoldello commented on src/encoded/static/components/cart/cart.js
> +            facet.terms = facetDisplay.sorter ? facetDisplay.sorter(facet.terms, files, analyses) : _(facet.terms).sortBy((facetTerm) => facetTerm.term.toLowerCase());
I looked at sorter function and it does not take in files...?

2021-03-05 23:12 UTC, forresttanaka commented on src/encoded/static/components/cart/cart.js
> +const analysisSorter = (facetTerms, files, analyses) => (
Hard to know what future sorting functions need, and I figured files was an overwhelmingly plausible one. It’s like SortTable, where most of the optional functions don’t use all the given parameters.

2021-03-06 06:22 UTC, zoldello requested changes
It would be better to have an alternative to having parameters not used...

2021-03-08 16:47 UTC, forresttanaka commented
Closing to address a crash.

2021-03-08 16:47 UTC, closed without merging