ENCD-5787-add-assays-GROcap-GROseq-long-read-scRNAseq-remove-snRNAseq…
ENCODE-DCC/encoded pull request #3791
Opened 2021-03-17 05:21 UTC by iyoungworth

…-genotyping-HTS

adjusted-expected-batch-download

refixed-expected-download

fixture-fix

batch-download-correction

batch-download-total-again

2021-03-17 18:05 UTC, gabdank requested changes

2021-03-17 18:05 UTC, gabdank commented on src/encoded/schemas/changelogs/award.md
> +### Schema version 8
the schema version should be 9 here

2021-03-17 18:15 UTC, iyoungworth commented on src/encoded/schemas/changelogs/award.md
> +### Schema version 8
Thanks for catching it! Updated

2021-03-17 19:15 UTC, gabdank approved these changes, later dismissed

2021-03-17 21:04 UTC, gabdank submitted a review, later dismissed

2021-03-18 05:46 UTC, gabdank approved these changes, later dismissed

2021-03-18 21:21 UTC, gabdank approved these changes

2021-03-19 00:32 UTC, merged