ENCD-5850-fix-analysis-title-and-permission
ENCODE-DCC/encoded pull request #3824
Opened 2021-03-31 21:49 UTC by yunhailuo

2021-03-31 22:10 UTC, jnau approved these changes

2021-03-31 22:17 UTC, jnau requested changes
code change looks fine. Indexing tests failing. Looks like something in tests needs to be changed as well

2021-04-01 00:04 UTC, forresttanaka submitted a review, later dismissed
It looks good.

2021-04-01 00:16 UTC, jnau approved these changes, later dismissed
tests passed and code changes look good

2021-04-05 22:30 UTC, keenangraham requested changes

2021-04-05 22:30 UTC, keenangraham commented on src/encoded/schemas/analysis.json
> +        {"$ref": "mixins.json#/attribution" },
Extra space in front for consistency.

2021-04-05 22:30 UTC, keenangraham commented on src/encoded/tests/data/inserts/expected_metadata.tsv
> +ENCFF003MRN	bam	bam		alignments	GRCh38	ENCSR123MRN	microRNA-seq	UBERON:0001891	midbrain	tissue	Homo sapiens	dexamethasone	60 nM	8 hour								miRNA					unstranded	2015-08-31	Roadmap			<30	1	1_1
Looks like expected annotation metadata also needs to be updated. Test failing.

2021-04-05 23:48 UTC, keenangraham submitted a review, later dismissed

2021-04-06 02:08 UTC, keenangraham commented
Make sure to rebase this over dev before merging. Some of the expected metadata tests might have to be updated now that SNO-197 is merged.

2021-04-07 23:34 UTC, keenangraham approved these changes

2021-04-07 23:36 UTC, merged