ENCD-6022-add-filter-type-and-filter-value-properties
ENCODE-DCC/encoded pull request #3990
Opened 2021-06-24 22:47 UTC by jenjou

2021-06-25 06:03 UTC, gabdank approved these changes

2021-06-25 20:37 UTC, gabdank requested changes
(can we have the enums change to be without underscores and add units?)
bin size (bp)
bin size (kb)
bin size (mb)
mapping quality
false discovery rate percentage

2021-06-28 18:33 UTC, gabdank submitted a review, later dismissed

2021-06-29 23:20 UTC, hitz approved these changes

2021-06-29 23:20 UTC, merged