ENCD-6055-FCC-series-search-update
ENCODE-DCC/encoded pull request #4039
Opened 2021-08-02 19:44 UTC by khzlin

2021-08-02 20:59 UTC, forresttanaka submitted a review, later dismissed

2021-08-09 21:05 UTC, forresttanaka requested changes
The first one’s optional, but I think we should reduce the code duplication in the second one — unless my replacement logic doesn't actually do the same thing, but I ran through it with different scenarios and don’t see a difference.

2021-08-09 21:05 UTC, forresttanaka commented on src/encoded/static/components/search.js
> +    const biosampleclassifications = result.biosample_ontology ? result.biosample_ontology[0].classification : '';
You don’t need to change this in this ticket, but with the deprecation of IE11, we’re now writing lines such as this with this weird-looking shortcut:
```
const biosampleclassifications = result.biosample_ontology?.[0].classification || '';
```
…which means the same as:
```
if (result.biosample_ontology) {
    biosampleclassifications = result.biosample_ontology[0].classification;
} else {
    biosampleclassifications = '';
}
```
This is more common when dereferencing elements of a deep object, so something like: `replicate?.library?.biosample` means “if replicate exists, get its library, and if that exists, get its biosample. If either of those are not the case, return undefined”; whereas `replicate.library.biosample` would simply crash if either replicate or library was undefined.

2021-08-09 21:05 UTC, forresttanaka commented on src/encoded/static/components/search.js
> +                        {!fccSeries && (organism || lifeSpec.length > 0) ?
This and the code below are the same, so you can combine these using this conditional instead of the two conditionals you have:
```
(!fccSeries && (organism || lifeSpec.length > 0)) || (biosampleclassifications !== 'cell line' && (organism || lifeSpec.length > 0))
```

2021-08-09 21:36 UTC, khzlin commented on src/encoded/static/components/search.js
> +    const biosampleclassifications = result.biosample_ontology ? result.biosample_ontology[0].classification : '';
noted for next time.

2021-08-09 21:37 UTC, khzlin commented on src/encoded/static/components/search.js
> +                        {!fccSeries && (organism || lifeSpec.length > 0) ?
added &&fccSeries to the conditon.

2021-08-09 21:49 UTC, forresttanaka approved these changes
🆒

2021-08-10 21:50 UTC, merged