ENCD-5687-add-replication-count-to-experiments-and-fcc-experiments
ENCODE-DCC/encoded pull request #4078
Opened 2021-08-25 16:10 UTC by forresttanaka

2021-08-25 18:22 UTC, keenangraham commented on src/encoded/types/shared_calculated_properties.py
> +    @calculated_property(schema={
Just to make sure. We want `replication_count=0` in objects even if they don't have `replicates` defined? For example: https://www.encodeproject.org/search/?type=Experiment&replicates!=*

2021-08-25 18:24 UTC, forresttanaka commented on src/encoded/types/shared_calculated_properties.py
> +    @calculated_property(schema={
That was my plan. Now that you mention it, I’m not sure if that’s a _good_ plan, but it was intentional.

2021-08-25 18:25 UTC, keenangraham commented on src/encoded/types/shared_calculated_properties.py
> +    def replication_count(self, replicates=[]):
Slight danger of using mutable default argument `replicates=[]`. I think usual idiom for something like this is `replicates=None`, then logic:
```python
if replicates is None:
    return 0 # or whatever you want
return len(replicates)
```

2021-08-25 18:25 UTC, keenangraham commented on src/encoded/tests/test_types_experiment.py
> +
Two lines.

2021-08-25 18:25 UTC, keenangraham commented on src/encoded/tests/test_types_experiment.py
> +
Two lines.

2021-08-25 18:25 UTC, keenangraham commented on src/encoded/tests/test_types_functional_characterization_experiment.py
> +
Two lines.

2021-08-25 18:26 UTC, keenangraham submitted a review, later dismissed
Looks good, a couple comments but no blockers.

2021-08-25 19:24 UTC, forresttanaka commented on src/encoded/types/shared_calculated_properties.py
> +    def replication_count(self, replicates=[]):
I see. I’ll make these changes later today and put it up for review again. I saw the previous function had only a one-line gap so I kept to that, but should have looked at more of the file.

2021-08-26 16:21 UTC, keenangraham submitted a review, later dismissed

2021-08-27 17:49 UTC, keenangraham requested changes

2021-08-27 17:49 UTC, keenangraham commented on src/encoded/types/shared_calculated_properties.py
> +        replicate_numbers = set()
Made a comment in ticket. I think there's an issue with counting technical replicates with a set, since the numbers themselves can repeat within a biological replicate:
<img width="419" alt="Screen Shot 2021-08-27 at 10 44 24 AM" src="https://user-images.githubusercontent.com/16053922/131168042-a764f911-3215-4d0b-a0ed-6f5559f950f1.png">

I think the specification wasn't clear on how to actually count these, but the independent total number of each seems like the only thing that makes sense across diverse experiments.

2021-08-27 17:54 UTC, forresttanaka commented on src/encoded/types/shared_calculated_properties.py
> +        replicate_numbers = set()
> but the independent total number of each seems like the only thing that makes sense across diverse experiments

I think that’s what this does, or do you mean something different? I mean, for example, the test case with two replicates, one with BR:1 and TR:1, and one with BR:2 and TR:1, it counts two biological and one technical replicate. Or do you mean the TR count should be 2 in this case?

2021-08-27 18:00 UTC, keenangraham commented on src/encoded/types/shared_calculated_properties.py
> +        replicate_numbers = set()
Right, in ticket @hitz said https://www.encodeproject.org/experiments/ENCSR005UON/ should be 3 and 15, but I think it would only be 3 and 11 with the set.

2021-08-27 18:03 UTC, hitz commented on src/encoded/types/shared_calculated_properties.py
> +    @calculated_property(schema={
I think replication_count=0 is fine.

2021-08-27 18:12 UTC, forresttanaka commented on src/encoded/types/shared_calculated_properties.py
> +        replicate_numbers = set()
Got it, and confirmed that count is 11.

2021-08-27 18:13 UTC, hitz commented on src/encoded/types/shared_calculated_properties.py
> +        replicate_numbers = set()
I think that it should not be a set because 3,1 is totally different from 2,1.  It's not symmetric.

2021-08-27 21:30 UTC, keenangraham commented on src/encoded/types/shared_calculated_properties.py
> +    def bio_replicate_count(self, request, replicates):
Probably more of a wrangling question but I wonder if `bio` and `tech` should be fully spelled out to match `biological_replicate` and `technical_replicate`.

2021-08-27 21:31 UTC, keenangraham commented on src/encoded/types/shared_calculated_properties.py
> +                replicateObject = request.embed(rep, '@@object')
Probably should be snake case.

2021-08-27 21:31 UTC, keenangraham submitted a review, later dismissed

2021-08-27 21:33 UTC, forresttanaka commented on src/encoded/types/shared_calculated_properties.py
> +    def bio_replicate_count(self, request, replicates):
Unprompted, I would have. This is the way @hitz spelled it in the ticket, so that’s the only reason why I did it that way.

2021-08-27 21:33 UTC, forresttanaka commented on src/encoded/types/shared_calculated_properties.py
> +                replicateObject = request.embed(rep, '@@object')
Yeah, I wondered about that. It’s very common throughout this file to do it that way though, so I thought there was an unspoken rule about it.

2021-08-27 21:39 UTC, forresttanaka commented
@keenangraham Thanks for all your help on this.

2021-08-31 20:57 UTC, merged