ENCD-6121-add-screen-tiling-reference
ENCODE-DCC/encoded pull request #4081
Opened 2021-08-26 16:29 UTC by khzlin

2021-08-26 17:45 UTC, bonitalam requested changes

2021-08-26 17:45 UTC, bonitalam commented on src/encoded/schemas/reference.json
> +            "description": "CRISPR screen guide RNA design modalities. Peak tiling = all possible grna in a selection of peaks. Full tiling = all possible grna across an entire region, including regu
I think anything after modalities can be added as a comment and moved from the description. I would also have "grna" be "gRNA" instead.

2021-08-26 17:45 UTC, bonitalam commented on src/encoded/schemas/reference.json
> +            "enum": [
Can you put these enums in alphabetical order for consistency?

2021-08-26 17:45 UTC, bonitalam commented on src/encoded/static/components/search.js
> +    const fileSetType = result['@type'][0];
I think the UI part of the ticket should be for Functional Characterization Experiment and Functional Characterization Series. I think Idan will clarify more on the Jira ticket.

2021-08-26 17:53 UTC, khzlin commented on src/encoded/schemas/reference.json
> +            "description": "CRISPR screen guide RNA design modalities. Peak tiling = all possible grna in a selection of peaks. Full tiling = all possible grna across an entire region, including regu
ok, fixed

2021-08-30 23:44 UTC, khzlin commented on src/encoded/static/components/search.js
> +    const fileSetType = result['@type'][0];
second commit titled "UI new specs" contains additional code for new specs.

2021-08-31 16:20 UTC, bonitalam submitted a review, later dismissed

2021-09-01 15:46 UTC, bonitalam approved these changes

2021-09-01 19:46 UTC, merged