ENCD-6160-snatac
ENCODE-DCC/encoded pull request #4120
Opened 2021-09-29 02:37 UTC by jenjou

2021-09-29 17:59 UTC, bonitalam requested changes
In addition to the comments in the PR

- File schema changelog should be updated
- Need to add all the new objects to loadxl https://github.com/ENCODE-DCC/encoded/blob/dev/src/encoded/loadxl.py 
- Need to add all new QC metrics to https://github.com/ENCODE-DCC/encoded/blob/dev/src/encoded/types/quality_metric.py
- Need to also update https://github.com/ENCODE-DCC/encoded/blob/dev/src/encoded/static/components/filegallery.js#L1821-L1866 with all the QC metrics

2021-09-29 17:59 UTC, bonitalam commented on src/encoded/schemas/sc_atac_alignment_quality_metric.json
> +
Can we remove this extra line here?

2021-09-29 17:59 UTC, bonitalam commented on src/encoded/schemas/sc_atac_alignment_quality_metric.json
> +
This extra line can be removed

2021-09-29 17:59 UTC, bonitalam commented on src/encoded/schemas/sc_atac_alignment_quality_metric.json
> +
Remove extra line

2021-09-29 17:59 UTC, bonitalam commented on src/encoded/schemas/sc_atac_alignment_quality_metric.json
> +        "mito_stats": {
Since these are attachments you will need to update https://github.com/ENCODE-DCC/encoded/blob/dev/src/encoded/static/components/quality_metric.js#L18-L68

2021-09-29 17:59 UTC, bonitalam commented on src/encoded/schemas/sc_atac_analysis_quality_metric.json
> +    },
Same comment about quality_metric.js needing to be updated

2021-09-29 17:59 UTC, bonitalam commented on src/encoded/schemas/sc_atac_library_complexity_quality_metric.json
> +    },
Same comment about quality_metric.js

2021-09-29 17:59 UTC, bonitalam commented on src/encoded/schemas/sc_atac_multiplet_quality_metric.json
> +    },
Same comment about quality_metric.js https://github.com/ENCODE-DCC/encoded/blob/dev/src/encoded/static/components/quality_metric.js#L18-L68

2021-09-29 17:59 UTC, bonitalam commented on src/encoded/schemas/sc_atac_read_quality_metric.json
> +    },
Same comment about quality_metric.js

2021-09-29 17:59 UTC, bonitalam commented on src/encoded/tests/test_file.py
> +def test_file_post_archr_project(testapp, archr_project_file):
Can you also please add a test for the mex file format type dependency?

2021-09-29 17:59 UTC, bonitalam commented on src/encoded/tests/data/inserts/sc_atac_alignment_quality_metric.json
> +        "samstats": "ENCFF150HADvENCFF315YLZ.IDRv2.pooled_common_IDRv2.narrowPeak.png",
A general comment about all of the test inserts - the file format for the attachment is image/png in your examples - but I think defined in the schemas it is pdf. Should you be able to accept either pdf or png?

2021-09-29 22:36 UTC, bonitalam approved these changes, later dismissed

2021-09-29 23:14 UTC, bonitalam approved these changes, later dismissed

2021-09-30 17:42 UTC, bonitalam requested changes
In addition to my other comment - for the new properties that accept attachments `barcode_pairs_multiplets` and `barcode_pairs_expanded` the relevant files need to be updated:

- https://github.com/ENCODE-DCC/encoded/blob/dev/src/encoded/loadxl.py#L124-L150
- https://github.com/ENCODE-DCC/encoded/blob/dev/src/encoded/static/components/quality_metric.js#L18-L68

2021-09-30 17:42 UTC, bonitalam commented on src/encoded/schemas/sc_atac_multiplet_quality_metric.json
> +                        "application/gzip"
I don't think this a supported MIME type from: https://github.com/ENCODE-DCC/encoded/blob/dev/src/encoded/schemas/generic_quality_metric.json#L47-L58

2021-09-30 20:12 UTC, bonitalam commented on src/encoded/static/components/quality_metric.js
> +    ],
The new multiplet quality metric properties with attachments still need to be added here @gabdank

2021-09-30 23:57 UTC, bonitalam requested changes

2021-09-30 23:57 UTC, bonitalam commented on src/encoded/static/components/quality_metric.js
> +        { excluded_barcodes: 'Excluded barcodes from multiplet filtering' },
I think this line needs to be removed, there is no `excluded_barcodes` property.

2021-10-01 00:16 UTC, bonitalam approved these changes, later dismissed

2021-10-01 23:14 UTC, bonitalam submitted a review, later dismissed

2021-10-02 00:15 UTC, hitz approved these changes

2021-10-02 00:15 UTC, merged