ENCD-6216-gm-updates
ENCODE-DCC/encoded pull request #4180
Opened 2021-11-04 23:03 UTC by jenjou

2021-11-09 02:58 UTC, gabdank requested changes

2021-11-09 02:58 UTC, gabdank commented on src/encoded/schemas/changelogs/genetic_modification.md
> +* Removed *replacement* and *inhibition* enums from *category* property, and upgraded *transgene insertion* to *insertion*, *activation* to *CRISPRa*, *disruption* to *CRISPR cutting*, and *binding*
I think CRISPRi is missing?

2021-11-09 02:58 UTC, gabdank commented on src/encoded/schemas/genetic_modification.json
> +                            "enum": ["CRISPR cutting", "interference", "CRISPRi"]
would not it make sense to break into 2: one for CRISPR (then it is CRISPRi or CRISPRcutting) and one for RNAi where it is ONLY interference?

2021-11-10 19:29 UTC, gabdank approved these changes, later dismissed

2021-11-16 05:52 UTC, gabdank approved these changes, later dismissed

2021-11-17 20:14 UTC, gabdank submitted a review, later dismissed

2021-11-18 19:56 UTC, hitz approved these changes
quick review after rebase

2021-11-18 19:56 UTC, merged