ENCD-6213-redesigned-home-page
ENCODE-DCC/encoded pull request #4220
Opened 2021-12-15 22:49 UTC by forresttanaka

2021-12-17 18:24 UTC, zoldello requested changes
Most of my comments can be ignored except on - **src/encoded/tests/features/home.feature. The new line is needed at the end of the file. It is minor but important it is there.**

Here are comment based on looking at the UI. Most if not all can be ignored
- On the UI, if put the screen-size in mobile mode (iPhone-size), the header text "Search the ENCODE Portal" is hard to see. It needs to have a high z-index

- Would it be a good idea to have the hoover-over title to have a. new color that make it remarkable from its neighbors. Making it just a little bigger does not truly help.

- In desktop-mode, us twitter so important it needs to be on the upper right?

- Rounded corner is great for developer... But we are dealing with scientist who work in labs. Would it be a good idea to shape the title like petri dishes or flasks?

- Why is the Weng's lab screen app-toggle not showing search with rounded corners like ENCODE search results have?

- Would it be a good idea to replace the sign in/create account text at the bottom with a login-icon as it is on the top; to be consistent?

- Hovering over the '?' in titles supposed to give me information about the title. Clicking on the title supposed to go to the page in question. Otherwise, the '?'-icon serves no purpose and an equivalent is needed on the last light-blue color row.

- The icons on the titles of the homepage supposed to be present on the pages they link to.

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/components/app.js
> +            isHomePage: this.state.context && this.state.context?.['@type']?.[0] === 'Portal',
This can be simplified to - 
`this.state.context?.['@type']?.[0]`

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/components/home/card_definitions.js
> + * CARD DEFNIITIONS
Typo. Supposed to be - DEF**I**NITIONS

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/components/home/card_definitions.js
> + * Each of the following objects defines the cards that appear in each section of the home page.
No 's' after _defines_ as _defines_ is singular and it's subject _objects_ is plural

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/components/home/index.js
> +    card: PropTypes.shape({
Good idea. We need to starting using this more.

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/components/home/screen.js
> +        document.addEventListener('click', onClickOutsideSuggestionsMenu, false);
Doing this will in a sense all the click event to every element as Javascript events bubble up. I have never seen it done this way before in react but I guess it is okay. Would useRef be an option?

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/components/hooks.js
> +        const item = typeof window !== 'undefined' ? window.sessionStorage.getItem(key) : null;
Some argue that if code cannot do what it supposed to do, it should not revert to doing something else; rather it should fail. If I use this thinking it is storing values in sessionstorage, but it is doing nothing but returning initialValue, it can lead to a bug.

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/components/hooks.js
> +export const useSessionStorage = (key, initialValue) => {
This is a good idea.

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/components/objectutils.js
> +export const postUri = (queryUri, payload) => (
since JSON-request calls should be frequent, can this be made generic to support POST, GET and PUT?

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/libs/timeout.js
> +        this._expiryCallback();
What happens if expirarcyCallback is null or undefined? The Timeout class is publicly accessible via export, so a consumer function can put in anything for the callBack, especially a non-function.

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/scss/encoded/modules/_home.scss
> +$CARD_GAP_WIDTH: 10px;
I personally prefer SCSS way of declaring variables. But there is an argument for supporting the way CSS-standard var; as we no longer need to worry about IE11.

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/scss/encoded/modules/_tooltip.scss
> +        font-size: 0;
font-size:0 is a code-smell. Why have the font in the first place?

2021-12-17 18:24 UTC, zoldello commented on src/encoded/tests/data/inserts/page.json
> +        "name": "testpage",
Is this as you intended. "homepage" seems better.

2021-12-17 18:24 UTC, zoldello commented on src/encoded/tests/features/home.feature
> +        # because failures in screen.wenglab.org will cause our BDD tests to fail.
Need ending new line.

2021-12-17 18:24 UTC, zoldello commented on src/encoded/static/components/app.js
> +            const ContentView = globals.contentViews.lookup(context, currentAction);
This might can be null via a future code change and cause the page to blow up if I am not mistake.

2021-12-17 19:29 UTC, forresttanaka commented
> On the UI, if put the screen-size in mobile mode (iPhone-size), the header text "Search the ENCODE Portal" is hard to see. It needs to have a high z-index

Yeah, it is difficult to read, though because of the background position on mobile, not because of the Z-index. I added a white glow around the text to make it stand out a little more.

> Would it be a good idea to have the hoover-over title to have a. new color that make it remarkable from its neighbors. Making it just a little bigger does not truly help.

I think it should highlight by size or by color. I feel like both is overkill.

> In desktop-mode, us twitter so important it needs to be on the upper right?

That’s what people wanted in a design meeting.

> Rounded corner is great for developer... But we are dealing with scientist who work in labs. Would it be a good idea to shape the title like petri dishes or flasks?

I personally feel that’s a little cheesy.

> Why is the Weng's lab screen app-toggle not showing search with rounded corners like ENCODE search results have?

Not sure what you mean. The search box you type into shows rounded corners for both ENCODE and SCREEN search results for me in Safari, Chrome, Firefox, and Safari mobile.

> Would it be a good idea to replace the sign in/create account text at the bottom with a login-icon as it is on the top; to be consistent?

I see the point, but I feel like it can be spelled out in the footer and an icon in the navigation bar. Not sure if all would agree.

> Hovering over the '?' in titles supposed to give me information about the title. Clicking on the title supposed to go to the page in question. Otherwise, the '?'-icon serves no purpose and an equivalent is needed on the last light-blue color row.

People didn’t want the ? in the bottom row. I don’t think we ever established that ? should always produce hovers. I’ve never heard that anyway. Clicking the ? shows help.

> The icons on the titles of the homepage supposed to be present on the pages they link to.

Maybe we will someday. That was never specified anywhere I’m aware of.

2021-12-17 19:30 UTC, forresttanaka commented on src/encoded/static/components/app.js
> +            isHomePage: this.state.context && this.state.context?.['@type']?.[0] === 'Portal',
Yes; I didn’t notice that.

2021-12-17 19:31 UTC, forresttanaka commented on src/encoded/static/components/app.js
> +            const ContentView = globals.contentViews.lookup(context, currentAction);
If ContentView gets null, it just won’t render anything, which is just a bug that needs fixing if it happens.

2021-12-17 19:33 UTC, forresttanaka commented on src/encoded/static/components/home/card_definitions.js
> + * Each of the following objects defines the cards that appear in each section of the home page.
Yes, that’s true.

2021-12-17 19:35 UTC, forresttanaka commented on src/encoded/static/components/home/screen.js
> +        document.addEventListener('click', onClickOutsideSuggestionsMenu, false);
I’ve seen it done this way several times, and I liked it. Not sure what you would attach the ref to, unless we add a viewport-covering div, which I felt wasn’t necessary here.

2021-12-17 19:38 UTC, forresttanaka commented on src/encoded/static/scss/encoded/modules/_home.scss
> +$CARD_GAP_WIDTH: 10px;
I was going to use CSS variables for the first time here, but ran into an issue that I don’t remember now (I should have written a note to myself) so I thought I’d hold off for now.

2021-12-17 19:40 UTC, forresttanaka commented on src/encoded/static/scss/encoded/modules/_tooltip.scss
> +        font-size: 0;
That’s an old hack for inline elements. I’ve seen alternatives, none of which I thought was very good. Maybe people have more modern ways. https://css-tricks.com/fighting-the-space-between-inline-block-elements/#set-the-font-size-to-zero

2021-12-17 19:40 UTC, forresttanaka commented on src/encoded/tests/data/inserts/page.json
> +        "name": "testpage",
That came from a branch from Laurence that I integrated. Seemed to not make a difference, but now that you mention it, I’m not sure if he had a specific reason for that.

2021-12-17 19:41 UTC, forresttanaka commented on src/encoded/tests/features/home.feature
> +        # because failures in screen.wenglab.org will cause our BDD tests to fail.
Done. Surprised I didn’t notice that.

2021-12-17 21:21 UTC, forresttanaka commented on src/encoded/static/components/objectutils.js
> +export const postUri = (queryUri, payload) => (
Probably could be. For IGVF we’ll have to think about request APIs more completely. For ENCODE it was all pretty piecemeal over the years.

2021-12-17 22:01 UTC, forresttanaka commented
New demo coming up, but won’t be ready until after hours, and rustybot will immediately stop it.

2021-12-17 22:10 UTC, zoldello approved these changes, later dismissed
Looks fine.

2022-01-05 17:50 UTC, zoldello approved these changes
Code looks good. The new changes after the last review address Idan's request for a period and are cosmetic.

2022-01-05 21:40 UTC, merged