Encd 5411 reverse sort
ENCODE-DCC/encoded pull request #4221
Opened 2021-12-16 15:14 UTC by mingjiecn

2022-01-04 16:56 UTC, forresttanaka requested changes, later dismissed
This looks fine, but just one extremely tiny formatting change.

2022-01-04 16:56 UTC, forresttanaka commented on src/encoded/static/components/facets/sort_desc.js
> +
Looks like two blank lines at the end of the file. Could you make it just one?

2022-02-04 23:30 UTC, hitz commented on src/encoded/static/components/facets/sort_desc.js
> +
oh this got missed but I am just going to merge it anyhow

2022-02-04 23:30 UTC, hitz approved these changes

2022-02-04 23:31 UTC, merged