ENCM-43 supersedes donor
ENCODE-DCC/encoded pull request #4284
Opened 2022-05-25 20:31 UTC by gabdank

2022-05-26 20:25 UTC, ian-whaling commented on src/encoded/schemas/fly_donor.json
> +            "comment": "The donor(s) in this list should be obsolete and the superseeding donoe object should be used instead.",
typo: "superseeding donoe" -> "superseding donor"

2022-05-26 20:26 UTC, ian-whaling requested changes
typos: "superseeding donoe" -> "superseding donor" in all comments of donor schemas

2022-05-26 23:23 UTC, gabdank commented on src/encoded/schemas/fly_donor.json
> +            "comment": "The donor(s) in this list should be obsolete and the superseeding donoe object should be used instead.",
fixed

2022-05-27 01:06 UTC, ian-whaling requested changes
"superseding" should only have one e.
https://github.com/ENCODE-DCC/encoded/blob/4c86845b3057d68f4ec8adc4a7f076bffa986674/src/encoded/schemas/analysis.json#L73

2022-05-31 16:38 UTC, ian-whaling submitted a review, later dismissed

2022-06-08 00:54 UTC, merged