ENCM-27 Show only released results for cards and home-page searches
ENCODE-DCC/encoded pull request #4315
Opened 2022-08-18 00:23 UTC by forresttanaka

Change Log

* Change “Experiment search” under the “Functional Characterization data” menu to show onlly released datasets.
* Adjust queue_worker_processes from 24 to 20 to avoid OOM errors on demo deploy.
* Add status=released to any home-page card searches that didn’t already have that.
* Update BDD tests for new home-page searches.

2022-08-22 16:13 UTC, mingjiecn approved these changes, later dismissed

2022-08-22 21:47 UTC, forresttanaka commented
@mingjiecn Code review update: Meenakshi found some links that still need “status=released” added, so I’ve added those so that all search-based menu items have status=released, except for RNA Get.

2022-08-22 22:17 UTC, mingjiecn commented on src/encoded/static/components/app.js
> +                { id: 'mouse-development-matrix', title: 'Mouse development matrix', url: '/mouse-development-matrix/?type=Experiment&status=released&related_series.@type=OrganismDevelopmentSeries&re
duplicated "status=released" in Mouse development matrix url

2022-08-22 22:20 UTC, mingjiecn requested changes
duplicated "status=released" in Mouse development matrix url

2022-08-23 00:40 UTC, forresttanaka commented
@mingjiecn Thanks for finding that duplication!

2022-08-23 13:52 UTC, mingjiecn approved these changes

2022-08-27 02:09 UTC, merged