ENCM-84 Make a matrix for Degron experiments
ENCODE-DCC/encoded pull request #4335
Opened 2022-11-08 23:31 UTC by forresttanaka

This is one of the simpler matrices in that it mostly follows what other matrices do. Even the basic Experiment matrix is more complicated because it has a nested Y and X axes where this one has only a nested X-axis. The important part is in matrix_degron.js. A lot of the other changed files generate data to test the Degron matrix locally.

2022-11-09 21:47 UTC, dougli1sqrd reviewed
The first thing I'm noticing is when I very first go to the Degron page the horizontal items are all squished together: Home page -> Data drop down to Degron link -> squished.

<img width="1044" alt="Screen Shot 2022-11-09 at 1 45 03 PM" src="https://user-images.githubusercontent.com/1422171/200948436-48c7adfd-ebb7-4fdc-8ffb-6915846357c5.png">

After a refresh on the page it behaves normally. But I can always reproduce by navigating away, and navigating back to the page (even with just forward and back buttons).
<img width="809" alt="Screen Shot 2022-11-09 at 1 46 33 PM" src="https://user-images.githubusercontent.com/1422171/200948659-92e386ac-dcbb-435f-b532-2b0bcaee40a4.png">

2022-11-09 21:54 UTC, forresttanaka commented
Oh, that’s a Safari thing apparently, which I forgot to test. I’ll need to fix that. Hopefully it’s not difficult.

2022-11-09 21:55 UTC, forresttanaka commented
Looks like Firefox has a different issue.

2022-11-09 22:02 UTC, dougli1sqrd commented
Should I also see cells filled in at all in that view that I screenshotted?

2022-11-09 22:03 UTC, forresttanaka commented
Yes, like it appears in Chrome.

2022-11-09 22:18 UTC, dougli1sqrd commented
ah yeah, looks like something is up in firefox then there

2022-11-09 23:01 UTC, forresttanaka commented
I have fixes for Safari and Firefox ready, so I’ll push those and whatever else we need once you’re done with code review.

2022-11-10 00:06 UTC, dougli1sqrd commented on src/encoded/static/components/matrix_degron.js
> +const composeColCategoryQuery = (context, colCategoryBucket, colSubcategoryBucket) => {
How come we say "context" for the search result object? Would another name that just describes the fact that it's the search results be more clear? Or is there a historical reason here?

2022-11-10 00:06 UTC, dougli1sqrd commented on src/encoded/static/components/matrix_degron.js
> +const COL_CATEGORY_DATA_SORT_ORDER = [
Why is this the sorting order? Maybe we should comment also how we know this so in case something has to change we know how we generated this order in the first place.

2022-11-10 00:08 UTC, forresttanaka commented on src/encoded/static/components/matrix_degron.js
> +const composeColCategoryQuery = (context, colCategoryBucket, colSubcategoryBucket) => {
“context” refers to any object from the back end. It got that name before I started and by that time it had already become ubiquitous through the code base. Laurence felt some regret calling it that once React also got the concept of a “context.”

2022-11-10 00:09 UTC, forresttanaka commented on src/encoded/static/components/matrix_degron.js
> +const COL_CATEGORY_DATA_SORT_ORDER = [
Ben defined the sorting order. I don’t know why it’s that order.

2022-11-10 00:17 UTC, dougli1sqrd commented on src/encoded/static/components/matrix_degron.js
> +const composeColCategoryQuery = (context, colCategoryBucket, colSubcategoryBucket) => {
ahh yeah okay. Yeah I did think at first it could be related to the react context, but we have that also.

2022-11-10 00:17 UTC, dougli1sqrd commented on src/encoded/static/components/matrix_degron.js
> +const COL_CATEGORY_DATA_SORT_ORDER = [
okay!

2022-11-10 00:19 UTC, dougli1sqrd approved these changes
Happy to take a look at your upcoming updates

2022-11-10 00:22 UTC, forresttanaka commented
Could you reject this PR ? Then I can put in the updates and re-request your review.

2022-11-10 00:34 UTC, dougli1sqrd requested changes
Approve for what's currently here, awaiting updates from earlier convo

2022-11-10 00:40 UTC, dougli1sqrd commented
does the demo get updated? Or should I try running this locally?

2022-11-10 00:41 UTC, forresttanaka commented
I updated the demo and it’s rebuilding right now. I’ll wait for the tests to pass before putting it back into code review.

2022-11-10 02:43 UTC, dougli1sqrd approved these changes, later dismissed
@forresttanaka this worked!

2022-11-10 21:32 UTC, dougli1sqrd submitted a review, later dismissed

2022-11-11 18:52 UTC, merged