ENCM-90 stem cell
ENCODE-DCC/encoded pull request #4372
Opened 2023-02-23 00:33 UTC by emro

Adds new graphs, new links, new descriptions, new colors, updated matricies

2023-02-23 17:11 UTC, forresttanaka requested changes
None of my comments require changes.

2023-02-23 17:11 UTC, forresttanaka commented on src/encoded/static/libs/ui/node_graph.js
> +}
I get some ESLint errors in this file, here for having `else` after a `return` as well as the missing semicolon at the end of the `nodeKeyname` function. Whether we care at this stage of encode is up to you. An error farther down I feel has a bit more importance.

2023-02-23 17:11 UTC, forresttanaka commented on src/encoded/static/libs/ui/node_graph.js
> +                .attr('class', (d) => `node-text`);
Unused variable `d`, but again, doesn’t matter much.

2023-02-23 17:11 UTC, forresttanaka commented on src/encoded/static/libs/ui/node_graph.js
> +                    .style('fill', (d) => d.data.selectedColor ? internalSelectedNodes.indexOf(nodeKeyName(d.data.name)) > -1 ? d.data.selectedColor : d.data.deselectedColor : 'unset')
This ESLint error (“Arrow function used ambiguously with a conditional expression”) does seem a little important. I find the order of execution unclear.

2023-02-23 17:11 UTC, forresttanaka commented on src/encoded/static/libs/ui/node_graph.js
> +    }
This is partly already established code, but here I think `else if` would have made sense to avoid the miniscule performance cost of assigning up to three different values to the same `textWrapWidth` variable.

2023-02-23 17:11 UTC, forresttanaka commented on src/encoded/static/libs/ui/node_graph.js
> +                    }
Another good place for an `else if`, again to avoid an extremely minimal cost of assigning multiple values to the same variable, `xOffset`.

2023-02-23 17:11 UTC, forresttanaka commented on src/encoded/static/components/matrix_sescc_stem_cell.js
> +    // const colCategoriesWithSubcategories = Object.keys(colMap).filter((colCategoryName) => colMap[colCategoryName].hasSubcategories && !collapsedAssays.includes(colCategoryName));
Looks like some stale comments and commented-out code I didn’t remove.

2023-02-23 17:11 UTC, forresttanaka commented on src/encoded/static/components/matrix_sescc_stem_cell.js
> +                    const fullHeight = selectedTab === 'h9' ? 530 : selectedTab === 'pgp' ? 500 : 300;
I’m unclear what the order of execution is, though I don’t see an ESLint error here, which surprises me.

2023-02-23 22:46 UTC, emro commented on src/encoded/static/components/matrix_sescc_stem_cell.js
> +    // const colCategoriesWithSubcategories = Object.keys(colMap).filter((colCategoryName) => colMap[colCategoryName].hasSubcategories && !collapsedAssays.includes(colCategoryName));
Deleted

2023-02-23 22:47 UTC, emro commented on src/encoded/static/libs/ui/node_graph.js
> +    }
I actually think we don't need this at all because the default is `textWrapWidth = 50`

2023-02-24 00:53 UTC, emro commented
I think I addressed everything! Thank you again so much for helping me fix the linting display on VS Code! This will make everything a million times easier for me.

2023-02-24 01:01 UTC, forresttanaka approved these changes, later dismissed

2023-02-25 00:36 UTC, forresttanaka approved these changes

2023-02-27 21:35 UTC, merged