ENCM-197-ting-wang-support
ENCODE-DCC/encoded pull request #4420
Opened 2024-01-23 14:46 UTC by khzlin

2024-01-24 18:18 UTC, gabdank requested changes
lower case for transposable elements

2024-01-24 18:18 UTC, gabdank commented on src/encoded/schemas/analysis_step.json
> +                    "Transposable Element TF ancestral origin percent by motif",
lower case "transposable element TF .."

2024-01-24 18:18 UTC, gabdank commented on src/encoded/schemas/analysis_step.json
> +                    "Transposable Element TF ancestral origin percent by motif",
lower case "transposable element TF ..."

2024-01-24 18:18 UTC, gabdank commented on src/encoded/schemas/changelogs/analysis_step.md
> +* Added *motif clusters reference*, *phastcons score reference*, *Transposable Element TF ancestral origin percent by motif*, *Transposable Element TF ancestral origin percent by subfamily* and *vari
lower case "transposable.."

2024-01-24 18:18 UTC, gabdank commented on src/encoded/schemas/changelogs/file.md
> +* Added *motif clusters reference*, *phastcons score reference*, *Transposable Element TF ancestral origin percent by motif*, *Transposable Element TF ancestral origin percent by subfamily*, *repeats
lower case

2024-01-24 18:18 UTC, gabdank commented on src/encoded/schemas/file.json
> +                        "Transposable Element TF ancestral origin percent by motif",
lower case

2024-01-24 18:18 UTC, gabdank commented on src/encoded/schemas/file.json
> +        "Transposable Element TF ancestral origin percent by motif": "annotation",
lower case

2024-01-24 18:18 UTC, gabdank commented on src/encoded/tests/data/inserts/analysis_step.json
> +                "Transposable Element TF ancestral origin percent by subfamily",
lower case

2024-01-24 18:18 UTC, gabdank commented on src/encoded/tests/data/inserts/expected_annotation_metadata.tsv
> +ENCFF002KEK	tsv	Transposable Element TF ancestral origin percent by motif		ENCSR767PSZ	transcription factor ancestral origin estimate									Homo sapiens		2023-03-15	ENCODE	Michael Snyder, Stanford
lower case

2024-01-24 18:18 UTC, gabdank commented on src/encoded/tests/data/inserts/file.json
> +        "output_type": "Transposable Element TF ancestral origin percent by motif",
lower case

2024-01-24 18:18 UTC, gabdank commented on src/encoded/tests/data/inserts/file.json
> +        "output_type": "Transposable Element TF ancestral origin percent by subfamily",
lower case

2024-01-24 19:02 UTC, khzlin commented on src/encoded/schemas/analysis_step.json
> +                    "Transposable Element TF ancestral origin percent by motif",
done

2024-01-24 19:02 UTC, khzlin commented on src/encoded/schemas/analysis_step.json
> +                    "Transposable Element TF ancestral origin percent by motif",
done

2024-01-24 19:03 UTC, khzlin commented on src/encoded/schemas/changelogs/analysis_step.md
> +* Added *motif clusters reference*, *phastcons score reference*, *Transposable Element TF ancestral origin percent by motif*, *Transposable Element TF ancestral origin percent by subfamily* and *vari
done

2024-01-24 19:03 UTC, khzlin commented on src/encoded/schemas/file.json
> +                        "Transposable Element TF ancestral origin percent by motif",
done

2024-01-24 19:03 UTC, khzlin commented on src/encoded/schemas/file.json
> +        "Transposable Element TF ancestral origin percent by motif": "annotation",
done

2024-01-24 19:03 UTC, khzlin commented on src/encoded/tests/data/inserts/expected_annotation_metadata.tsv
> +ENCFF002KEK	tsv	Transposable Element TF ancestral origin percent by motif		ENCSR767PSZ	transcription factor ancestral origin estimate									Homo sapiens		2023-03-15	ENCODE	Michael Snyder, Stanford
done

2024-01-24 19:03 UTC, khzlin commented on src/encoded/tests/data/inserts/file.json
> +        "output_type": "Transposable Element TF ancestral origin percent by subfamily",
done

2024-01-24 19:07 UTC, khzlin commented on src/encoded/schemas/changelogs/file.md
> +* Added *motif clusters reference*, *phastcons score reference*, *Transposable Element TF ancestral origin percent by motif*, *Transposable Element TF ancestral origin percent by subfamily*, *repeats
done

2024-01-24 19:07 UTC, khzlin commented on src/encoded/tests/data/inserts/file.json
> +        "output_type": "Transposable Element TF ancestral origin percent by motif",
done

2024-01-31 19:10 UTC, gabdank submitted a review, later dismissed

2024-02-06 01:17 UTC, gabdank approved these changes, later dismissed

2024-02-28 00:04 UTC, gabdank approved these changes

2024-02-28 00:05 UTC, merged